apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: apps
spec:
  components:
  - name: apps
    type: kustomize
    properties:
      repoType: git
      url: https://github.com/qlans/samples/tree/master/09.GitOps_Demo/for-SREs
      secretRef: git-secret
      pullInterval: 1m
      git:
        branch: main
      path: ./apps
