apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: infra
spec:
  components:
  - name: database-config
    type: kustomize
    properties:
      repoType: git
      url: https://github.com/qlans/samples/tree/master/09.GitOps_Demo/for-SREs
      secretRef: git-secret
      pullInterval: 10m
      git:
        branch: main
      path: ./infrastructure
